-- =============================================================
-- ESQUEMA COMPLETO DE TABLAS PARA SUPABASE (NESTOR Y PAME)
-- =============================================================

-- 1. Tabla: configuracion_general
CREATE TABLE IF NOT EXISTS configuracion_general (
  id TEXT PRIMARY KEY,
  nombres_novios TEXT DEFAULT 'Nestor y Pame',
  welcome_text TEXT DEFAULT 'Bienvenidos a nuestra invitación',
  frase_amor TEXT DEFAULT 'Hay momentos en la vida que son especiales por sí solos, pero compartirlos con las personas que queremos los hace inolvidables.',
  frase_visible BOOLEAN DEFAULT TRUE,
  updated_by TEXT,
  updated_at TIMESTAMPTZ
);

-- 2. Tabla: evento
CREATE TABLE IF NOT EXISTS evento (
  id TEXT PRIMARY KEY,
  fecha TEXT DEFAULT '2026-10-24',
  horario TEXT DEFAULT '17:45',
  hora_finalizacion TEXT DEFAULT '04:00',
  lugar TEXT DEFAULT 'Las Moras Eventos',
  direccion TEXT DEFAULT 'Mateo Blanco 369, Campana, Buenos Aires',
  maps_url TEXT DEFAULT 'https://maps.google.com/?q=Las+Moras+Eventos+Mateo+Blanco+369+Campana',
  dress_code_tipo TEXT DEFAULT 'Elegante',
  dress_code_texto TEXT DEFAULT 'Queremos que te sientas cómodo y elegante para compartir esta noche con nosotros.',
  dress_code_colores TEXT DEFAULT 'Por favor, reservar los colores blanco y bordo para los protagonistas y la ambientación.',
  dress_code_nota TEXT DEFAULT 'No es necesario utilizar los colores de la invitación. Solo te pedimos evitar blanco y bordo.'
);

-- 3. Tabla: enlaces
CREATE TABLE IF NOT EXISTS enlaces (
  id TEXT PRIMARY KEY,
  instagram_user TEXT DEFAULT 'nestorypame2026',
  instagram_url TEXT DEFAULT 'https://instagram.com/nestorypame2026',
  instagram_hashtag TEXT DEFAULT '#NestoryPame',
  instagram_text TEXT DEFAULT 'Seguinos en Instagram para compartir la previa del gran día.',
  instagram_visible BOOLEAN DEFAULT TRUE,
  compartir_fotos_url TEXT DEFAULT 'https://photos.google.com/',
  compartir_fotos_visible BOOLEAN DEFAULT TRUE,
  sugerir_canciones_url TEXT DEFAULT 'https://open.spotify.com/playlist/6v4DSTXLcXvtaqdUaNyQtI?si=DG0YFn4oRf-22BDSiOOg6Q',
  sugerir_canciones_modalidad TEXT DEFAULT 'interno',
  sugerir_canciones_visible BOOLEAN DEFAULT TRUE,
  google_sheets_url TEXT DEFAULT ''
);

-- 4. Tabla: regalos
CREATE TABLE IF NOT EXISTS regalos (
  id TEXT PRIMARY KEY,
  alias TEXT DEFAULT 'casamiento.nestor.pame',
  titular TEXT DEFAULT 'Nestor y Pame',
  banco TEXT DEFAULT 'Banco Galicia',
  cbu_cvu TEXT DEFAULT '0070000000000000000000',
  texto_regalos TEXT DEFAULT 'El mejor regalo es compartir este momento con nosotros. Pero si además querés ayudarnos a cumplir nuestros próximos sueños, te dejamos nuestros datos bancarios.',
  visible BOOLEAN DEFAULT TRUE
);

-- 5. Tabla: musica
CREATE TABLE IF NOT EXISTS musica (
  id TEXT PRIMARY KEY,
  cancion_url TEXT DEFAULT 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
  cancion_nombre TEXT DEFAULT 'Te conocí',
  artista TEXT DEFAULT 'Zenar y Dario Coiro',
  volumen_inicial NUMERIC DEFAULT 0.5,
  visible BOOLEAN DEFAULT TRUE,
  loop BOOLEAN DEFAULT TRUE,
  autoplay_welcome BOOLEAN DEFAULT TRUE
);

-- 6. Tabla: fotografias
CREATE TABLE IF NOT EXISTS fotografias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL,
  orden INTEGER DEFAULT 0,
  posicion_encuadre TEXT DEFAULT 'center',
  tipo TEXT DEFAULT 'galeria',
  visible BOOLEAN DEFAULT TRUE,
  state TEXT DEFAULT 'draft',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Tabla: confirmaciones
CREATE TABLE IF NOT EXISTS confirmaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dni TEXT NOT NULL UNIQUE,
  nombre TEXT NOT NULL,
  apellido TEXT NOT NULL,
  asiste BOOLEAN DEFAULT TRUE,
  menores INTEGER DEFAULT 0,
  restricciones_alimentarias TEXT DEFAULT 'Ninguna',
  comentarios TEXT,
  fecha_respuesta TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Tabla: canciones_sugeridas
CREATE TABLE IF NOT EXISTS canciones_sugeridas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cancion TEXT NOT NULL,
  artista TEXT,
  invitado TEXT,
  comentario TEXT,
  fecha TIMESTAMPTZ DEFAULT NOW(),
  estado TEXT DEFAULT 'nueva'
);

-- 9. Tabla: mensajes (Libro de firmas)
CREATE TABLE IF NOT EXISTS mensajes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  autor TEXT NOT NULL,
  mensaje TEXT NOT NULL,
  fecha_creacion TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Tabla: historial_cambios
CREATE TABLE IF NOT EXISTS historial_cambios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_modificacion TIMESTAMPTZ DEFAULT NOW(),
  usuario TEXT DEFAULT 'admin@nestorypame.com',
  accion TEXT,
  detalle TEXT
);

-- =============================================================
-- INSERCIÓN DE DATOS SEMILLA (DRAFT Y PUBLISHED)
-- =============================================================

-- Semilla: configuracion_general
INSERT INTO configuracion_general (id, nombres_novios, welcome_text, frase_amor, frase_visible)
VALUES 
('draft', 'Nestor y Pame', 'Bienvenidos a nuestra invitación', 'Hay momentos en la vida que son especiales por sí solos, pero compartirlos con las personas que queremos los hace inolvidables.', TRUE),
('published', 'Nestor y Pame', 'Bienvenidos a nuestra invitación', 'Hay momentos en la vida que son especiales por sí solos, pero compartirlos con las personas que queremos los hace inolvidables.', TRUE)
ON CONFLICT (id) DO NOTHING;

-- Semilla: evento
INSERT INTO evento (id, fecha, horario, hora_finalizacion, lugar, direccion, maps_url, dress_code_tipo, dress_code_texto, dress_code_colores, dress_code_nota)
VALUES 
('draft', '2026-10-24', '17:45', '04:00', 'Las Moras Eventos', 'Mateo Blanco 369, Campana, Buenos Aires', 'https://maps.google.com/?q=Las+Moras+Eventos+Mateo+Blanco+369+Campana', 'Elegante', 'Queremos que te sientas cómodo y elegante para compartir esta noche con nosotros.', 'Por favor, reservar los colores blanco y bordo para los protagonistas y la ambientación.', 'No es necesario utilizar los colores de la invitación. Solo te pedimos evitar blanco y bordo.'),
('published', '2026-10-24', '17:45', '04:00', 'Las Moras Eventos', 'Mateo Blanco 369, Campana, Buenos Aires', 'https://maps.google.com/?q=Las+Moras+Eventos+Mateo+Blanco+369+Campana', 'Elegante', 'Queremos que te sientas cómodo y elegante para compartir esta noche con nosotros.', 'Por favor, reservar los colores blanco y bordo para los protagonistas y la ambientación.', 'No es necesario utilizar los colores de la invitación. Solo te pedimos evitar blanco y bordo.')
ON CONFLICT (id) DO NOTHING;

-- Semilla: enlaces
INSERT INTO enlaces (id, instagram_user, instagram_url, instagram_hashtag, instagram_text, instagram_visible, compartir_fotos_url, compartir_fotos_visible, sugerir_canciones_url, sugerir_canciones_modalidad, sugerir_canciones_visible, google_sheets_url)
VALUES 
('draft', 'nestorypame2026', 'https://instagram.com/nestorypame2026', '#NestoryPame', 'Seguinos en Instagram para compartir la previa del gran día.', TRUE, 'https://photos.google.com/', TRUE, 'https://open.spotify.com/playlist/6v4DSTXLcXvtaqdUaNyQtI?si=DG0YFn4oRf-22BDSiOOg6Q', 'interno', TRUE, ''),
('published', 'nestorypame2026', 'https://instagram.com/nestorypame2026', '#NestoryPame', 'Seguinos en Instagram para compartir la previa del gran día.', TRUE, 'https://photos.google.com/', TRUE, 'https://open.spotify.com/playlist/6v4DSTXLcXvtaqdUaNyQtI?si=DG0YFn4oRf-22BDSiOOg6Q', 'interno', TRUE, '')
ON CONFLICT (id) DO NOTHING;

-- Semilla: regalos
INSERT INTO regalos (id, alias, titular, banco, cbu_cvu, texto_regalos, visible)
VALUES 
('draft', 'casamiento.nestor.pame', 'Nestor y Pame', 'Banco Galicia', '0070000000000000000000', 'El mejor regalo es compartir este momento con nosotros. Pero si además querés ayudarnos a cumplir nuestros próximos sueños, te dejamos nuestros datos bancarios.', TRUE),
('published', 'casamiento.nestor.pame', 'Nestor y Pame', 'Banco Galicia', '0070000000000000000000', 'El mejor regalo es compartir este momento con nosotros. Pero si además querés ayudarnos a cumplir nuestros próximos sueños, te dejamos nuestros datos bancarios.', TRUE)
ON CONFLICT (id) DO NOTHING;

-- Semilla: musica
INSERT INTO musica (id, cancion_url, cancion_nombre, artista, volumen_inicial, visible, loop, autoplay_welcome)
VALUES 
('draft', 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', 'Te conocí', 'Zenar y Dario Coiro', 0.5, TRUE, TRUE, TRUE),
('published', 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', 'Te conocí', 'Zenar y Dario Coiro', 0.5, TRUE, TRUE, TRUE)
ON CONFLICT (id) DO NOTHING;

-- Semilla: fotografias (Imágenes de muestra por defecto)
INSERT INTO fotografias (url, orden, posicion_encuadre, tipo, visible, state)
VALUES
('https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=800', 0, 'center', 'portada', TRUE, 'draft'),
('https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=800', 0, 'center', 'portada', TRUE, 'published'),
('https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&q=80&w=600', 0, 'center', 'galeria', TRUE, 'draft'),
('https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&q=80&w=600', 0, 'center', 'galeria', TRUE, 'published'),
('https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&q=80&w=600', 1, 'center', 'galeria', TRUE, 'draft'),
('https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&q=80&w=600', 1, 'center', 'galeria', TRUE, 'published');
